### ISSUE TITLE
guacamole的数据库认证没有生效

### ISSUE THREAD

**Issue by xiongchuanyang** [TelDragon/guacamole#2]
你好，我在部署的过程中遇到了一个问题。照着文档的部署步骤进行部署。但是最后mysql认证没有生效
catalina.out日志报错如下：
![image](https://user-images.githubusercontent.com/38678481/51035236-4a03ca80-15e4-11e9-8a10-bf1df69ff61f.png)
不知道问题时出在哪里？

**Comment by TelDragon** [comment]
@xiongchuanyang 
是这样，之前我部署的时候也遇到过类似的情况，我之前的原因是可能因为mysql 版本太高所不支持，后修改为 5.6 。
你的这个报错信息可能是以为没有做 文件的指向，查看下 你的 etc下是否有这个文件夹并且给予了权限。
